import { relative } from 'node:path';
import type { ClassInfo } from '../types.js';
import { emitBuilderClass } from './builder.js';
import { emitDataConstructor } from './data.js';
import { emitDeclarationShim } from './declaration.js';
import { builderClassName, hasClassDecorator, visibleFields } from './helpers.js';

function toImportPath(sourcePath: string, cwd: string): string {
  let rel = relative(cwd, sourcePath).replace(/\\/g, '/');
  if (!rel.startsWith('.')) rel = './' + rel;
  return rel.replace(/\.ts$/u, '');
}

function emitToStringFn(info: ClassInfo): string {
  if (!hasClassDecorator(info, 'ToString') && !hasClassDecorator(info, 'Data')) return '';
  const fields = visibleFields(info);
  const parts = fields.map((f) => `${f.name}=\${String(this.${f.name})}`).join(', ');
  return `
function ${info.name}_toString(this: ${info.name}): string {
  return \`${info.name}(${parts})\`;
}`.trim();
}

function emitApplyMixin(info: ClassInfo): string {
  const assignments: string[] = [];

  if (hasClassDecorator(info, 'Data')) {
    for (const f of info.fields) {
      const g = `get${f.name.charAt(0).toUpperCase()}${f.name.slice(1)}`;
      assignments.push(`prototype.${g} = ${info.name}_${g};`);
      if (!f.isReadonly) {
        const s = `set${f.name.charAt(0).toUpperCase()}${f.name.slice(1)}`;
        assignments.push(`prototype.${s} = ${info.name}_${s};`);
      }
    }
    assignments.push(`prototype.equals = ${info.name}_equals;`);
    assignments.push(`prototype.toString = ${info.name}_toString;`);
  } else if (hasClassDecorator(info, 'ToString')) {
    assignments.push(`prototype.toString = ${info.name}_toString;`);
  }

  if (hasClassDecorator(info, 'Builder')) {
    const bName = builderClassName(info.name);
    assignments.push(
      `(ctor as typeof ${info.name} & { builder(): ${bName} }).builder = ${info.name}_builder;`,
    );
  }

  if (assignments.length === 0) return '';

  return `
export function apply${info.name}Generated(ctor: typeof ${info.name}): void {
  const prototype = ctor.prototype;
  ${assignments.join('\n  ')}
}`.trim();
}

function emitDataFns(info: ClassInfo): string {
  if (!hasClassDecorator(info, 'Data')) return '';

  const fns: string[] = [];

  if (info.fields.length > 0) {
    fns.push(
      emitDataConstructor(info)
        .replace(/^\s*constructor/m, `function ${info.name}_init`)
        .replace(/\)$/m, ')'),
    );
    // Skip - constructor can't be assigned easily. Use generated constructor note in docs.
  }

  for (const f of info.fields) {
    const g = `get${f.name.charAt(0).toUpperCase()}${f.name.slice(1)}`;
    fns.push(
      `
function ${info.name}_${g}(this: ${info.name}): ${f.type} {
  return this.${f.name};
}`.trim(),
    );
    if (!f.isReadonly) {
      const s = `set${f.name.charAt(0).toUpperCase()}${f.name.slice(1)}`;
      fns.push(
        `
function ${info.name}_${s}(this: ${info.name}, value: ${f.type}): void {
  this.${f.name} = value;
}`.trim(),
      );
    }
  }

  const equalsBody = info.fields.map((f) => `this.${f.name} === other.${f.name}`).join(' &&\n    ');

  fns.push(
    `
function ${info.name}_equals(this: ${info.name}, other: ${info.name} | null | undefined): boolean {
  if (other === null || other === undefined) return false;
  if (!(other instanceof (this.constructor as typeof ${info.name}))) return false;
  return ${equalsBody || 'true'};
}`.trim(),
  );

  fns.push(emitToStringFn(info));

  return fns.filter(Boolean).join('\n\n');
}

function emitBuilderFn(info: ClassInfo): string {
  if (!hasClassDecorator(info, 'Builder')) return '';
  const bName = builderClassName(info.name);
  return `
function ${info.name}_builder(): ${bName} {
  return ${bName}.builder();
}`.trim();
}

export function emitCompanionFile(
  sourcePath: string,
  classes: readonly ClassInfo[],
  cwd: string,
): { ts: string; dts: string } {
  const header = [
    '// Auto-generated by lombok-typescript.',
    '// Source: ' + relative(cwd, sourcePath).replace(/\\/g, '/'),
    '// Do not edit. Regenerate via `lombok-ts generate`.',
    '',
  ].join('\n');

  const importPath = toImportPath(sourcePath, cwd);
  const typeImports = classes.map((c) => c.name).join(', ');
  const imports = `import type { ${typeImports} } from '${importPath}';\n\n`;

  const blocks: string[] = [];

  for (const info of classes) {
    const builder = emitBuilderClass(info);
    if (builder) blocks.push(builder);

    if (hasClassDecorator(info, 'Data')) {
      blocks.push(emitDataFns(info));
    } else {
      const ts = emitToStringFn(info);
      if (ts) blocks.push(ts);
    }

    const builderFn = emitBuilderFn(info);
    if (builderFn) blocks.push(builderFn);

    const apply = emitApplyMixin(info);
    if (apply) blocks.push(apply);
  }

  const applyAll =
    classes.filter((c) => emitApplyMixin(c)).length > 0
      ? `\n\nexport function applyAllGenerated(handlers: {\n${classes
          .filter((c) => emitApplyMixin(c))
          .map((c) => `  ${c.name}: typeof ${c.name};`)
          .join('\n')}\n}): void {\n${classes
          .filter((c) => emitApplyMixin(c))
          .map((c) => `  apply${c.name}Generated(handlers.${c.name});`)
          .join('\n')}\n}\n`
      : '\nexport {};\n';

  const ts = header + imports + blocks.join('\n\n') + applyAll;
  const dts = emitDeclarationShim(sourcePath, classes, cwd);

  return { ts, dts };
}

export { emitDeclarationShim };
