import { mkdtempSync, readFileSync, rmSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { CodeGenerator } from './generator.js';
import { LombokTransformer } from './transformer.js';

describe('CodeGenerator', () => {
  let tmpDir: string;
  let prevCwd: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'lombok-test-'));
    prevCwd = process.cwd();
    process.chdir(tmpDir);
  });

  afterEach(() => {
    process.chdir(prevCwd);
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it('uses sensible defaults', () => {
    const gen = new CodeGenerator();
    expect(gen.options.outputDir).toBe('.lombok');
    expect(gen.options.include).toEqual(['src/**/*.ts']);
    expect(gen.options.exclude).toContain('**/*.test.ts');
    expect(gen.options.tsConfigPath).toBe('tsconfig.json');
  });

  it('merges user options over defaults', () => {
    const gen = new CodeGenerator({ outputDir: 'custom-out' });
    expect(gen.options.outputDir).toBe('custom-out');
    expect(gen.options.tsConfigPath).toBe('tsconfig.json');
  });

  describe('generate() with files on disk', () => {
    function writeSrc(rel: string, content: string) {
      const full = join(tmpDir, rel);
      mkdirSync(join(tmpDir, rel.split('/').slice(0, -1).join('/')), { recursive: true });
      writeFileSync(full, content, 'utf8');
      return full;
    }

    it('emits a companion file for each source containing classes', async () => {
      writeSrc(
        'src/user.ts',
        `
@MarkerA
class User {
  @MarkerB
  name: string = '';
}
`,
      );

      const gen = new CodeGenerator({ tsConfigPath: 'no-such-tsconfig.json' });
      const generated = await gen.generate();

      expect(generated).toHaveLength(1);
      expect(generated[0]!.processedClasses).toEqual(['User']);

      const outPath = join(tmpDir, '.lombok', 'src', 'user.lombok.ts');
      expect(existsSync(outPath)).toBe(true);
      const content = readFileSync(outPath, 'utf8');
      expect(content).toContain('Auto-generated by lombok-typescript');
      expect(content).toContain('export {}');
      expect(content).not.toContain('import ');
      expect(existsSync(outPath.replace(/\.lombok\.ts$/u, '.lombok.d.ts'))).toBe(true);
    });

    it('skips files that contain no classes', async () => {
      writeSrc('src/no-class.ts', 'export const x = 1;');
      const gen = new CodeGenerator({ tsConfigPath: 'no-such-tsconfig.json' });
      const generated = await gen.generate();
      expect(generated).toHaveLength(0);
    });

    it('skips test files via the default exclude list', async () => {
      writeSrc(
        'src/sample.test.ts',
        `
@Marker
class TestOnly {}
`,
      );
      const gen = new CodeGenerator({ tsConfigPath: 'no-such-tsconfig.json' });
      const generated = await gen.generate();
      expect(generated).toHaveLength(0);
    });

    it('processes multiple classes in a single file', async () => {
      writeSrc(
        'src/multi.ts',
        `
@A
class One {}
@B
class Two {}
`,
      );
      const gen = new CodeGenerator({ tsConfigPath: 'no-such-tsconfig.json' });
      const generated = await gen.generate();
      expect(generated).toHaveLength(1);
      expect(generated[0]!.processedClasses).toEqual(['One', 'Two']);

      const content = readFileSync(generated[0]!.outputPath, 'utf8');
      expect(content).toContain('export {}');
      expect(content).not.toContain('import ');
    });

    it('uses in-memory project when tsconfig is missing', async () => {
      writeSrc(
        'src/only.ts',
        `@A
class Only { value: number; }`,
      );
      const gen = new CodeGenerator({ tsConfigPath: 'missing-tsconfig.json' });
      const generated = await gen.generate();
      expect(generated).toHaveLength(1);
    });

    it('writes companion files under the configured outputDir', async () => {
      writeSrc(
        'src/foo.ts',
        `@A
class Foo {}`,
      );
      const gen = new CodeGenerator({
        tsConfigPath: 'no-such-tsconfig.json',
        outputDir: 'custom-gen',
      });
      const generated = await gen.generate();
      expect(generated[0]!.outputPath).toContain('custom-gen');
      expect(existsSync(join(tmpDir, 'custom-gen', 'src', 'foo.lombok.ts'))).toBe(true);
    });
  });

  describe('generateForFile()', () => {
    it('processes a single file and returns the generated output', async () => {
      const file = join(tmpDir, 'standalone.ts');
      writeFileSync(
        file,
        `@Marker
class Solo {
  field: number = 1;
}`,
        'utf8',
      );

      const gen = new CodeGenerator({ tsConfigPath: 'no-such-tsconfig.json' });
      const result = await gen.generateForFile(file);

      expect(result).not.toBeNull();
      expect(result!.processedClasses).toEqual(['Solo']);
      expect(existsSync(result!.outputPath)).toBe(true);
    });

    it('returns null for a file with no classes', async () => {
      const file = join(tmpDir, 'empty.ts');
      writeFileSync(file, 'export const x = 1;', 'utf8');

      const gen = new CodeGenerator({ tsConfigPath: 'no-such-tsconfig.json' });
      const result = await gen.generateForFile(file);

      expect(result).toBeNull();
    });
  });

  describe('watch()', () => {
    it('throws a clear "not implemented yet" error', async () => {
      const gen = new CodeGenerator();
      await expect(gen.watch()).rejects.toThrow(/Watch mode is not implemented yet/);
    });
  });
});

describe('LombokTransformer', () => {
  it('throws a clear "not implemented yet" error when constructed', () => {
    expect(() => new LombokTransformer()).toThrow(/not implemented yet/);
  });
});
