import { mkdtempSync, readFileSync, rmSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { CodeGenerator } from './generator.js';
import { LombokTransformer } from './transformer.js';

class ExposedGenerator extends CodeGenerator {
  shouldProcessPublic(filePath: string): boolean {
    return this.shouldProcess(filePath);
  }

  renderCompanionPublic(
    sourcePath: string,
    classes: Parameters<CodeGenerator['renderCompanion']>[1],
  ) {
    return this.renderCompanion(sourcePath, classes);
  }
}

describe('CodeGenerator', () => {
  let tmpDir: string;
  let prevCwd: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'lombok-test-'));
    prevCwd = process.cwd();
    process.chdir(tmpDir);
  });

  afterEach(() => {
    process.chdir(prevCwd);
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it('uses sensible defaults', () => {
    const gen = new CodeGenerator();
    expect(gen.options.outputDir).toBe('.lombok');
    expect(gen.options.include).toEqual(['src/**/*.ts']);
    expect(gen.options.exclude).toContain('**/*.test.ts');
    expect(gen.options.tsConfigPath).toBe('tsconfig.json');
  });

  it('merges user options over defaults', () => {
    const gen = new CodeGenerator({ outputDir: 'custom-out' });
    expect(gen.options.outputDir).toBe('custom-out');
    expect(gen.options.tsConfigPath).toBe('tsconfig.json');
  });

  describe('generate() with files on disk', () => {
    function writeSrc(rel: string, content: string) {
      const full = join(tmpDir, rel);
      mkdirSync(join(tmpDir, rel.split('/').slice(0, -1).join('/')), { recursive: true });
      writeFileSync(full, content, 'utf8');
      return full;
    }

    it('emits a companion file for each source containing classes', async () => {
      writeSrc(
        'src/user.ts',
        `
@MarkerA
class User {
  @MarkerB
  name: string = '';
}
`,
      );

      const gen = new CodeGenerator({ tsConfigPath: 'no-such-tsconfig.json' });
      const generated = await gen.generate();

      expect(generated).toHaveLength(1);
      expect(generated[0]!.processedClasses).toEqual(['User']);

      const outPath = join(tmpDir, '.lombok', 'src', 'user.lombok.ts');
      expect(existsSync(outPath)).toBe(true);
      const content = readFileSync(outPath, 'utf8');
      expect(content).toContain('Auto-generated by lombok-typescript');
      expect(content).toContain('export {}');
      expect(content).not.toContain('import ');
      expect(existsSync(outPath.replace(/\.lombok\.ts$/u, '.lombok.augment.d.ts'))).toBe(true);
    });

    it('skips files that contain no classes', async () => {
      writeSrc('src/no-class.ts', 'export const x = 1;');
      const gen = new CodeGenerator({ tsConfigPath: 'no-such-tsconfig.json' });
      const generated = await gen.generate();
      expect(generated).toHaveLength(0);
    });

    it('skips test files via the default exclude list', async () => {
      writeSrc(
        'src/sample.test.ts',
        `
@Marker
class TestOnly {}
`,
      );
      const gen = new CodeGenerator({ tsConfigPath: 'no-such-tsconfig.json' });
      const generated = await gen.generate();
      expect(generated).toHaveLength(0);
    });

    it('processes multiple classes in a single file', async () => {
      writeSrc(
        'src/multi.ts',
        `
@A
class One {}
@B
class Two {}
`,
      );
      const gen = new CodeGenerator({ tsConfigPath: 'no-such-tsconfig.json' });
      const generated = await gen.generate();
      expect(generated).toHaveLength(1);
      expect(generated[0]!.processedClasses).toEqual(['One', 'Two']);

      const content = readFileSync(generated[0]!.outputPath, 'utf8');
      expect(content).toContain('export {}');
      expect(content).not.toContain('import ');
    });

    it('uses in-memory project when tsconfig is missing', async () => {
      writeSrc(
        'src/only.ts',
        `@A
class Only { value: number; }`,
      );
      const gen = new CodeGenerator({ tsConfigPath: 'missing-tsconfig.json' });
      const generated = await gen.generate();
      expect(generated).toHaveLength(1);
    });

    it('writes companion files under the configured outputDir', async () => {
      writeSrc(
        'src/foo.ts',
        `@A
class Foo {}`,
      );
      const gen = new CodeGenerator({
        tsConfigPath: 'no-such-tsconfig.json',
        outputDir: 'custom-gen',
      });
      const generated = await gen.generate();
      expect(generated[0]!.outputPath).toContain('custom-gen');
      expect(existsSync(join(tmpDir, 'custom-gen', 'src', 'foo.lombok.ts'))).toBe(true);
    });
  });

  describe('generateForFile()', () => {
    it('processes a single file and returns the generated output', async () => {
      const file = join(tmpDir, 'standalone.ts');
      writeFileSync(
        file,
        `@Marker
class Solo {
  field: number = 1;
}`,
        'utf8',
      );

      const gen = new CodeGenerator({ tsConfigPath: 'no-such-tsconfig.json' });
      const result = await gen.generateForFile(file);

      expect(result).not.toBeNull();
      expect(result!.processedClasses).toEqual(['Solo']);
      expect(existsSync(result!.outputPath)).toBe(true);
    });

    it('returns null for a file with no classes', async () => {
      const file = join(tmpDir, 'empty.ts');
      writeFileSync(file, 'export const x = 1;', 'utf8');

      const gen = new CodeGenerator({ tsConfigPath: 'no-such-tsconfig.json' });
      const result = await gen.generateForFile(file);

      expect(result).toBeNull();
    });
  });

  describe('watch()', () => {
    function writeSrc(rel: string, content: string) {
      const full = join(tmpDir, rel);
      mkdirSync(join(tmpDir, rel.split('/').slice(0, -1).join('/')), { recursive: true });
      writeFileSync(full, content, 'utf8');
      return full;
    }

    it('generates companions and resolves when aborted', async () => {
      writeSrc(
        'src/watch-me.ts',
        `@Data
class WatchMe { id: string; }`,
      );
      const gen = new CodeGenerator({ tsConfigPath: 'no-such-tsconfig.json' });
      const controller = new AbortController();
      const logs: string[] = [];
      const promise = gen.watch({ log: (m) => logs.push(m), signal: controller.signal });
      controller.abort();
      await promise;
      expect(logs.join('\n')).toMatch(/Watching for changes/i);
      expect(existsSync(join(tmpDir, '.lombok', 'src', 'watch-me.lombok.ts'))).toBe(true);
    });

    it('returns before watching when the abort signal is already set', async () => {
      writeSrc('src/early-abort.ts', 'class EarlyAbort {}');
      const gen = new CodeGenerator({ tsConfigPath: 'no-such-tsconfig.json' });
      const controller = new AbortController();
      controller.abort();
      await gen.watch({ signal: controller.signal });
    });

    it('regenerates companions when a watched file changes', async () => {
      const srcPath = writeSrc(
        'src/live.ts',
        `@Data
class Live { id: string; }`,
      );
      const outPath = join(tmpDir, '.lombok', 'src', 'live.lombok.ts');
      const gen = new CodeGenerator({ tsConfigPath: 'no-such-tsconfig.json' });
      const controller = new AbortController();
      const logs: string[] = [];
      const done = gen.watch({ log: (m) => logs.push(m), signal: controller.signal });

      await new Promise((resolve) => setTimeout(resolve, 150));

      expect(readFileSync(outPath, 'utf8')).toContain('getId');
      expect(readFileSync(outPath, 'utf8')).not.toContain('getName');

      writeFileSync(
        srcPath,
        `@Data
class Live { id: string; name: string; }`,
        'utf8',
      );

      await new Promise((resolve) => setTimeout(resolve, 400));

      expect(readFileSync(outPath, 'utf8')).toContain('getName');
      expect(logs.some((line) => /Regenerated/i.test(line))).toBe(true);

      controller.abort();
      await done;
    }, 10_000);
  });

  describe('shouldProcess() and renderCompanion()', () => {
    it('respects include and exclude globs', () => {
      const gen = new ExposedGenerator({
        include: ['src/**/*.ts'],
        exclude: ['**/*.test.ts', 'dist'],
      });
      expect(gen.shouldProcessPublic(join(tmpDir, 'src', 'app.ts'))).toBe(true);
      expect(gen.shouldProcessPublic(join(tmpDir, 'src', 'app.test.ts'))).toBe(false);
      expect(gen.shouldProcessPublic(join(tmpDir, 'dist', 'app.js'))).toBe(false);
      expect(gen.shouldProcessPublic(join(tmpDir, 'other', 'app.ts'))).toBe(false);
    });

    it('allows all files when include is empty', () => {
      const gen = new ExposedGenerator({ include: [], exclude: [] });
      expect(gen.shouldProcessPublic(join(tmpDir, 'anywhere.ts'))).toBe(true);
    });

    it('renderCompanion returns a stub export', () => {
      const gen = new ExposedGenerator();
      expect(gen.renderCompanionPublic('src/x.ts', [])).toBe('export {};\n');
    });
  });

  it('loads source files from an existing tsconfig', async () => {
    mkdirSync(join(tmpDir, 'src'), { recursive: true });
    writeFileSync(join(tmpDir, 'src', 'from-tsconfig.ts'), 'class FromTs {}', 'utf8');
    writeFileSync(
      join(tmpDir, 'tsconfig.json'),
      JSON.stringify({ compilerOptions: { target: 'ES2022' }, include: ['src/**/*.ts'] }),
      'utf8',
    );

    const gen = new CodeGenerator({ tsConfigPath: 'tsconfig.json' });
    const generated = await gen.generate();

    expect(generated).toHaveLength(1);
    expect(generated[0]!.processedClasses).toEqual(['FromTs']);
  });
});

describe('LombokTransformer', () => {
  it('throws a clear "not implemented yet" error when constructed', () => {
    expect(() => new LombokTransformer()).toThrow(/not implemented yet/);
  });
});
