#!/usr/bin/env node
/**
 * Sync src/version.ts from package.json so CLI_VERSION and VERSION match the release.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const pkg = JSON.parse(readFileSync(resolve('package.json'), 'utf8'));
const version = pkg.version;

const contents = `// Generated by scripts/gen-version.mjs — do not edit.
export const VERSION = '${version}';
export const CLI_VERSION = '${version}';
`;

writeFileSync(resolve('src/version.ts'), contents);
console.log(`gen-version: ${version}`);
